### ISSUE TITLE
Make traits influenceable in both directions, not just "up."

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/CollegeSim#10]

**Comment by mbrown7** [comment]
I believe that this is already implemented. In Group::influenceMembers( ), we have a variable "increment" which is some random number times (averageValue - memberValue). The thing that was making it so traits could only be influenced up was a "the difference must be positive" in the if-statement which I took out when we first were talking about this.

We still have the concern that "increment" is calculated using a random double divided by 52 for independent and by 5 for dependent. I'm sure the discrepancy is a typo, but which should we keep? They're arbitrary but just affect whether we drift "a little" or "a lot" at a time.

**Comment by divilian** [comment]
```
I agree the 52 is a typo, since it doesn't agree with the comment. Lol
```

Maddie.

```
I suppose the increment (or at least the divisor "5" part) should be
```

another parameter, since right now we can only configure the probability that
you'll drift, not how far you'd drift. And the two are interrelated,
obviously: drifting on average 1/104th of the way to your neighbor seems very
small...unless you're doing this every single month, in which case the two of
you are probably going to converge in nothing flat. Wdyt?
- Stephen

mbrown7 wrote:

**Comment by mbrown7** [comment]
This makes sense to me.

**Comment by divilian** [comment]
Okay, I will add this as another parameter to the display.

**Comment by mbrown7** [comment]
(The email reply works!)
