### ISSUE TITLE
Add "increment" by which a person drifts to the UI.

### ISSUE THREAD

**Issue by mbrown7** [WheezePuppet/CollegeSim#13]
Please note that there is an increment in Group as well as in Person. If we wanted to change things around we could have just one increment in Sim that we access, or we could just set them separately with a single option, or have them both configurable.

See Group::influenceMembers( ) and Person::personalityDrift( ).

**Comment by divilian** [comment]
Confused as to exactly what the "increment" _is_, and therefore stuck.

**Comment by divilian** [comment]
Added in 6319ab147b92f0db2cbb5c447e50986eee115233.
